# pod.yaml

---
apiVersion: v1   <=== 指定使用 v1 版本的 api
kind: Pod        <=== 指定類型為 Pod
metadata:        <=== 將 Pod 命名為 cache，並加入 app:cache 的標記
  name: cache
  labels:
    app: cache
spec:                <=== 規格描述
  containers:        <=== 描述容器
  - name: redis   <=== 將容器命名為 redis
    image: redis:latest     <=== 使用 redis 映像檔
    ports:
    - containerPort: 6379   <=== 指定使用 6379 port
